// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RatesUIClient is the client API for RatesUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatesUIClient interface {
	// ListEngineSpecs returns a list of Rating Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RatesUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type ratesUIClient struct {
	cc grpc.ClientConnInterface
}

func NewRatesUIClient(cc grpc.ClientConnInterface) RatesUIClient {
	return &ratesUIClient{cc}
}

func (c *ratesUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (RatesUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RatesUI_ServiceDesc.Streams[0], "/v1.RatesUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &ratesUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RatesUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type ratesUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *ratesUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ratesUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.RatesUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatesUIServer is the server API for RatesUI service.
// All implementations must embed UnimplementedRatesUIServer
// for forward compatibility
type RatesUIServer interface {
	// ListEngineSpecs returns a list of Rating Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, RatesUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedRatesUIServer()
}

// UnimplementedRatesUIServer must be embedded to have forward compatible implementations.
type UnimplementedRatesUIServer struct {
}

func (UnimplementedRatesUIServer) ListEngineSpecs(*ListEngineSpecsRequest, RatesUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedRatesUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedRatesUIServer) mustEmbedUnimplementedRatesUIServer() {}

// UnsafeRatesUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatesUIServer will
// result in compilation errors.
type UnsafeRatesUIServer interface {
	mustEmbedUnimplementedRatesUIServer()
}

func RegisterRatesUIServer(s grpc.ServiceRegistrar, srv RatesUIServer) {
	s.RegisterService(&RatesUI_ServiceDesc, srv)
}

func _RatesUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatesUIServer).ListEngineSpecs(m, &ratesUIListEngineSpecsServer{stream})
}

type RatesUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type ratesUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *ratesUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RatesUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatesUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.RatesUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatesUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatesUI_ServiceDesc is the grpc.ServiceDesc for RatesUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatesUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RatesUI",
	HandlerType: (*RatesUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _RatesUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _RatesUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rates-ui.proto",
}
